name: Using Environments
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  Dev-Job:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Run on dev
        run: echo Hello, DEV!
        
  Prod-Job:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Run on dev
        run: echo Hello, PROD!
